apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-api-slice
  labels:
    kubernetes.io/service-name: external-api
addressType: IPv4
ports:
- name: https
  protocol: TCP
  port: 443
endpoints:
- addresses:
  - "10.0.1.10"
  conditions:
    ready: true
  hostname: api-server-1
- addresses:
  - "10.0.1.11"
  conditions:
    ready: true
  hostname: api-server-2
