apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-memory-limit-range
  namespace: development
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 64Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
  - max:
      cpu: "4"
      memory: 4Gi
    min:
      cpu: 200m
      memory: 128Mi
    type: Pod
  - max:
      storage: 10Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
