apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: default
  labels:
    app: myapp
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-serviceaccount
  namespace: kube-system
secrets:
- name: admin-secret
